language: go
go:
  - 1.12.4
env:
  - GO111MODULE=on
addons:
  sonarcloud:
    organization: 030-github
    token:
      secure: $SONAR_TOKEN
script:
  - diff -u <(echo -n) <(gofmt -d ./)
  - go test -short -cover -v -coverprofile=coverage.out -covermode=atomic ./...