version: '3.7'
services:
  n3dr:
    image: utrecht/n3dr:3.0.0
    volumes:
      - ~/.n3dr.yaml:/home/n3dr/.n3dr.yaml
      - ~/2019-05-20-nexus-fqdn:/download
    environment:
      - HTTPS_PROXY=some-proxy
    command: repositories -n http://localhost:9999 -u admin -v ${NEXUS_API_VERSION} -b