---
name: Dive CI
'on': push
jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image efficiency
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t utrecht/n3dr:${{ github.sha }} .
      - name: Dive
        uses: yuichielectric/dive-action@0.0.4
        with:
          image: utrecht/n3dr:${{ github.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
