---
name: Dive CI
'on': push
jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image efficiency
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t utrecht/n3dr:${{ github.sha }} .
      - uses: 030/dive-action@v0.1.0
        with:
          image: utrecht/n3dr:${{ github.sha }}
