---
name: Dockle
'on': push
jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image using dockle
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Build image
        run: docker build -t utrecht/n3dr:${{ github.sha }} .
      - uses: goodwithtech/dockle-action@v0.1.2
        with:
          image: utrecht/n3dr:${{ github.sha }}
          ignore: CIS-DI-0005,CIS-DI-0006
          accept-key: libcrypto3,libssl3
