---
name: Dockle
'on': push
jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image using dockle
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t utrecht/n3dr:${{ github.sha }} .
      - uses: hands-lab/dockle-action@v1
        with:
          image: utrecht/n3dr:${{ github.sha }}
