---
name: Go
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-10.15
            shasum: shasum -a 512
          - os: ubuntu-20.04
            shasum: sha512sum
          - os: ubuntu-20.04
            shasum: sha512sum
          - os: windows-2019
            shasum: sha512sum
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.0
      - name: Unit tests
        run: go test ./... -cover
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
      - name: Set N3DR deliverable environment variable
        run: echo "n3dr-deliverable=n3dr-${{ matrix.os }}" >> $GITHUB_ENV
      - name: Use the value
        run: |
          echo "${{ env.n3dr-deliverable }}"
      - name: Build
        run: ./scripts/build.sh
        env:
          N3DR_DELIVERABLE: ${{ env.n3dr-deliverable }}
          SHA512_CMD: ${{ matrix.shasum }}
      - name: Quality
        run: |
          docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:v0.7.1 */*.sh -x
          docker run --rm -v ${PWD}:/data markdownlint/markdownlint:0.11.0 \
            README.md -s /data/.markdownlint.rb
          docker run --rm -v $(pwd):/data cytopia/yamllint:1.26-0.8 .
          docker run --rm -v $(pwd):/app -w /app -e GOFLAGS=-buildvcs=false \
            golangci/golangci-lint:v1.49.0-alpine golangci-lint run -v \
            --timeout 2m30s
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
