name: Go
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-10.15
            nexus-version: 3.9.0
            nexus-api-version: beta
            shasum: shasum -a 512
          - os: ubuntu-20.04
            nexus-version: 3.29.0
            nexus-api-version: v1
            shasum: sha512sum
          - os: ubuntu-20.04
            nexus-version: 3.9.0
            nexus-api-version: beta
            shasum: sha512sum
          - os: windows-2019
            nexus-version: 3.9.0
            nexus-api-version: beta
            shasum: sha512sum
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.7
      - name: Install bats
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install bats -y
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
      - name: Build
        run: ./scripts/build.sh
        env:
          SHA512_CMD: ${{ matrix.shasum }}
      - name: Unit test
        run: go test -short -cover -v -coverprofile=coverage.txt -covermode=atomic ./...
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
      - name: Integration test
        run: ./test/integration-tests.sh
        env:
          NEXUS_VERSION: ${{ matrix.nexus-version }}
          NEXUS_API_VERSION: ${{ matrix.nexus-api-version }}
          N3DR_APT_GPG_SECRET: ${{ secrets.N3DR_APT_GPG_SECRET }}
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
