---
name: golang
'on':
  # required by gomod-go-version-updater to trigger this action once pr has
  # been reviewed
  pull_request_review:
    types: [submitted]
  push:
jobs:
  mcvs-golang-action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.1.5
      - uses: schubergphilis/mcvs-golang-action@v0.4.1
        with:
          golang-unit-tests-exclusions: |-
            \(cmd\/n3dr\|internal\/app\/n3dr\/\(goswagger\|n3drtest\)\)
