---
name: Golang
'on': push
jobs:
  mcvs-golang-action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: schubergphilis/mcvs-golang-action@v0.3.1
        with:
          golang-unit-tests-exclusions: |-
            \(cmd\/n3dr\|internal\/app\/n3dr\/\(goswagger\|n3drtest\)\)
