---
name: Hadolint
'on': push
jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image using hadolint
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
