---
name: Integration
'on': push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.19.0
      - name: Install bats
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install bats -y
      - name: Integration test
        run: |
          ./test/integration-tests.sh
        env:
          N3DR_DELIVERABLE: ${{ env.n3dr-deliverable }}
          NEXUS_VERSION: ${{ matrix.nexus-version }}
          N3DR_APT_GPG_SECRET: ${{ secrets.N3DR_APT_GPG_SECRET }}
