name: Release
on:
  push:
    tags:
      - "*"
jobs:
  release:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-10.15
            shasum: shasum -a 512
          - os: ubuntu-20.04
            shasum: sha512sum
          - os: windows-2019
            shasum: sha512sum
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.7
      - name: Set N3DR deliverable environment variable
        run: echo "n3dr-deliverable=n3dr-${{ matrix.os }}" >> $GITHUB_ENV
      - name: Create release
        run: ./scripts/build.sh
        env:
          N3DR_DELIVERABLE: ${{ env.n3dr-deliverable }}
          GITHUB_TAG: ${{ github.ref }}
          SHA512_CMD: ${{ matrix.shasum }}
        if: ${{ startsWith(matrix.os, 'mac') || startsWith(matrix.os, 'ubuntu') }}
      - name: Create release windows
        run: |
          go build -ldflags "-X github.com/030/n3dr/cmd.Version=${GITHUB_TAG}" -o "${N3DR_DELIVERABLE}"
          $SHA512_CMD "${N3DR_DELIVERABLE}" > "${N3DR_DELIVERABLE}.sha512.txt"
          chmod +x "${N3DR_DELIVERABLE}"
        env:
          N3DR_DELIVERABLE: ${{ env.n3dr-deliverable }}
          GITHUB_TAG: ${{ github.ref }}
          SHA512_CMD: ${{ matrix.shasum }}
        if: ${{ startsWith(matrix.os, 'windows') }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ env.n3dr-deliverable }}
          asset_name: ${{ env.n3dr-deliverable }}
          tag: ${{ github.ref }}
      - name: Upload checksums
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ env.n3dr-deliverable }}.sha512.txt
          asset_name: ${{ env.n3dr-deliverable }}.sha512.txt
          tag: ${{ github.ref }}
