---
name: Release
on:
  push:
    tags:
      - "*"
jobs:
  release:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-10.15
            shasum: shasum -a 512
          - os: ubuntu-20.04
            shasum: sha512sum
          - os: windows-2019
            shasum: sha512sum
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.2-alpine3.13-alpine3.13-alpine3.13
      - name: Set N3DR deliverable environment variable
        run: echo "n3dr-deliverable=n3dr-${{ matrix.os }}" >> $GITHUB_ENV
        if: |
          ${{ startsWith(matrix.os, 'mac') || startsWith(matrix.os, 'ubuntu') }}
      - name: Set N3DR deliverable environment variable on Windows
        run: echo "n3dr-deliverable=n3dr-${{ matrix.os }}" >> $env:GITHUB_ENV
        if: ${{ startsWith(matrix.os, 'windows') }}
      - name: Use the value
        run: |
          echo "${{ env.n3dr-deliverable }}"
      - name: Create release
        run: ./scripts/build.sh
        env:
          N3DR_DELIVERABLE: ${{ env.n3dr-deliverable }}
          GITHUB_TAG: ${{ github.ref }}
          SHA512_CMD: ${{ matrix.shasum }}
        if: |
          ${{ startsWith(matrix.os, 'mac') || startsWith(matrix.os, 'ubuntu') }}
      - name: Create release windows
        shell: cmd
        run: |
          echo "GITHUB_TAG: '${{ github.ref }}'"
          echo "N3DR_DELIVERABLE: '${{ env.n3dr-deliverable }}'"
          cd cmd/n3dr
          go build -ldflags "-X main.Version=${{ github.ref }}" \
            -o "${{ env.n3dr-deliverable }}"
          sha512sum "${{ env.n3dr-deliverable }}" >\
            "${{ env.n3dr-deliverable }}.sha512.txt"
          chmod +x "${{ env.n3dr-deliverable }}"
          ls n3dr-windows-2019
        if: ${{ startsWith(matrix.os, 'windows') }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cmd/n3dr/${{ env.n3dr-deliverable }}
          asset_name: ${{ env.n3dr-deliverable }}
          tag: ${{ github.ref }}
      - name: Upload checksums
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cmd/n3dr/${{ env.n3dr-deliverable }}.sha512.txt
          asset_name: ${{ env.n3dr-deliverable }}.sha512.txt
          tag: ${{ github.ref }}
