name: Release
on:
  push:
    tags:
      - "*"
jobs:
  release:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-10.15
          - ubuntu-20.04
          - windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        run: ./scripts/build.sh
        env:
          N3DR_DELIVERABLE: n3dr-${{ matrix.os }}
          GITHUB_TAG: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          name: noti.darwinrelease
          path: release/noti.darwinrelease
