---
name: Snapcraft
'on':
  workflow_run:
    workflows: ['Release']
    push:
      tags:
        - '*'
    types:
      - completed
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # yamllint disable rule:line-length
      - name: Remove Docker
        run: |
          # https://github.com/canonical/lxd-cloud/blob/f20a64a8af42485440dcbfd370faf14137d2f349/test/includes/lxd.sh#L13-L23
          sudo rm -rf /etc/docker
          sudo apt-get purge moby-buildx moby-engine moby-cli moby-compose moby-containerd moby-runc -y
          sudo iptables -P FORWARD ACCEPT
      - uses: snapcore/action-build@v1
        with:
          path: build/package
        id: snapcraft
      - run: |
          sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
          n3dr --version | grep "[0-9]\."
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.SNAPCRAFT_LOGIN }}
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: 7/stable
