---
name: snapcraft
'on':
  push:
    tags:
      - 7.**
jobs:
  release:
    uses: ./.github/workflows/release.yml
  snapcraft:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: snapcore/action-build@v1
        with:
          path: build/package
        id: snapcraft
      - run: |
          sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
          n3dr --version | grep "[0-9]\."
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.SNAPCRAFT_LOGIN }}
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: candidate
